### ISSUE TITLE
Action: Remove cause application to crash if an opc was loaded twice

### ISSUE THREAD

**Issue by NoxMortem** [pro3d-space/PRo3D#174]
Importing the same opc twice, and then removing the opc via Action: Remove causes the application to crash
2x:
![grafik](https://user-images.githubusercontent.com/6750572/155355566-92d317b4-1086-4fe4-9e5f-212eef79b630.png)

Reproduced in:
- 4.2.0-prerelease1
- 4.0.3
- 4.6.1-prerelease1

 ```
 System.Collections.Generic.KeyNotFoundException: could not get key: 65f4eb76-97e7-4878-a548-5a7f37011a57
   at FSharp.Data.Adaptive.AMapModule.find@1422.Invoke(FSharpHashMap`2 m)
   at FSharp.Data.Adaptive.AValModule.MapVal`2.Compute(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t)
   at FSharp.Data.Adaptive.AValModule.BindVal`2.Compute(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t)
   at FSharp.Data.Adaptive.AValModule.BindVal`2.Compute(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t)
   at FSharp.Data.Adaptive.AValModule.BindVal`2.Compute(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t)
   at FSharp.Data.Adaptive.AValModule.MapVal`2.Compute(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t)
   at FSharp.Data.Adaptive.AValModule.Map2Val`3.Compute(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token)
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t)
   at Aardvark.Rendering.ShaderReflection.ShaderParameterWriter.Bind@424-1.PerformWrite(AdaptiveToken token, IntPtr target)
   at Aardvark.Rendering.ShaderReflection.ShaderParameterWriter.AdaptiveWriter.Write(AdaptiveToken token, IntPtr target)
   at Aardvark.Rendering.ShaderReflection.ShaderParameterWriter.AdaptiveWriter.Aardvark.Rendering.ShaderReflection.IAdaptiveWriter.Write(AdaptiveToken token, IntPtr target)
   at <StartupCode$Aardvark-Rendering-GL>.$ResourceManager.CreateUniformBuffer@96-1.Create(AdaptiveToken token, RenderToken rt, FSharpOption`1 old)
   at Aardvark.Rendering.Resource`2.PerformUpdate(AdaptiveToken token, RenderToken t)
   at Aardvark.Rendering.Resource`2.ForceUpdate(AdaptiveToken token, RenderToken rt)
   at <StartupCode$Aardvark-Rendering>.$ResourceManagement.action@1-15[h,v](Resource`2 x, Unit unitVar0)
   at Aardvark.Rendering.Resource`2.AddRef()
   at Aardvark.Rendering.ResourceCache`2.GetOrCreateLocalWrapped[x,y](FSharpList`1 key, FSharpFunc`2 create, FSharpFunc`2 wrap)
   at Aardvark.Rendering.ResourceCache`2.GetOrCreateLocal(FSharpList`1 key, FSharpFunc`2 create)
   at Aardvark.Rendering.ResourceCache`2.GetOrCreate(FSharpList`1 key, FSharpFunc`2 create)
   at Aardvark.Rendering.GL.PreparedPipelineStateModule.mapping@1-1(ResourceManager x, IUniformProvider uniforms, Scope scope, String tupledArg0, GLSLUniformBuffer tupledArg1)
   at Aardvark.Rendering.GL.PreparedPipelineStateModule.ResourceManager.CreateUniformBuffers(ResourceManager x, InterfaceSlots iface, IUniformProvider uniforms, Scope scope)
   at Aardvark.Rendering.GL.PreparedPipelineStateModule.ofRenderObject(IFramebufferSignature fboSignature, ResourceManager x, RenderObject rj)
   at Aardvark.Rendering.GL.PreparedCommandModule.ofRenderObject@1207(Boolean owned, IFramebufferSignature fboSignature, ResourceManager x, IRenderObject o)
   at Aardvark.GeoSpatial.Opc.PatchLod.preparePatch@219(PatchNode n, Int32 height, IRuntime runtime, RenderObject ro, IAdaptiveValue`1 attributeParams, Object lodContext, RenderPatch p)
   at Aardvark.GeoSpatial.Opc.PatchLod.prepare@404-1.Invoke(Unit unitVar)
   at FSharp.Data.Adaptive.Load Builder.Delay@321-3.Invoke(Unit unitVar0)
   at FSharp.Data.Adaptive.ProcModule.delay@579.Invoke(Unit unitVar)
   at Aardvark.Base.Monads.State.Delay@264-7.Run(s& state)
   at FSharp.Data.Adaptive.Load.Runner`1.processEvent(IObservable source, Object value)
   at FSharp.Data.Adaptive.Load.Runner`1.step(Time tTarget)
   at FSharp.Data.Adaptive.Load.Runner`1.Step(Time t)
   at FSharp.Data.Adaptive.Load.Runner`1.FSharp.Data.Adaptive.Load.IRunner.Step(Time t)
   at FSharp.Data.Adaptive.Load.runner@246(Runner this, Int32 id, CancellationToken token, Unit unitVar0)
   at FSharp.Data.Adaptive.Load.clo@259-15.Invoke(Unit _arg1)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 416
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncPrimitives.Start@907-1.Invoke(ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 177
   at <StartupCode$FSharp-Core>.$Async.-ctor@169-2.Invoke(Object o) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 171
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
isOpc: "...MslGaleDem_01_04\.visionary"
isOpc: "...MslGaleDem_01_04\MslGaleDem_01_04_000_000"
```

I am not saying that loading the same opc twice should be a supported use case - but a crash is not nice either ;).

**Comment by haraldsteinlechner** [comment]
finally, we solved this one (in the 4.11.0-prerelease4, after testing we will make an official release)... see https://github.com/pro3d-space/PRo3D/issues/277 for more information
