### ISSUE TITLE
SequBookmarks Generate Images causes Unhandled exception. System.Exception: reactivate Snapshots

### ISSUE THREAD

**Issue by NoxMortem** [pro3d-space/PRo3D#175]
Scene: [Victoria Crater](http://download.vrvis.at/acquisition/32987e2792e0/PRo3D/VictoriaCrater.zip)
Pro3D Scene attached
Location: SequBookmark: 1
Version: 4.6.1-prerelease1

```
 0: [Arguments] Exit on finish: yes
 0: [Arguments] Render depth: no
 0: [Arguments] Using linear magnification filtering: yes
 0: [Arguments] Show exploration centre: no
 0: [Arguments] Show reference system: no
 0: [Arguments] Output folder: E:\repositories\Pro3D\bin\Debug\net5.0\images
 0: [Arguments] Surface paths are valid: yes
 0: [Arguments] Snapshot path is valid: yes
ApplicationData: C:\Users\Kevin Streicher\AppData\Roaming
LocalApplicationData: C:\Users\Kevin Streicher\AppData\Local
 0: Running with AppData: C:\Users\Kevin Streicher\AppData\Roaming\Pro3D
 0: Color palette favorite colors are stored here: C:\Users\Kevin Streicher\AppData\Roaming\Pro3D\favoriteColors.js
Init Aardium at: C:\Users\Kevin Streicher\AppData\Roaming\Aardium-2_0_5
 0: initializing aardvark ....................................................
 0:   System Information:
 0:     System:      Microsoft Windows 10.0.19044
 0:     Processor:   16 core x64
 0:     Process:     x64
 0:     Framework:   .NET 5.0.14
 0:   Loading plugins ................................................ 0.033 s
 0:   initializing Constants ......................................... 0.007 s
 0:   initializing CustomPicklerProvider ............................. 0.036 s
 0:   initializing PixImageSharp ..................................... 0.023 s
 0:   initializing PixImageDevil ..................................... 0.019 s
 0:   initializing Loader ....................................................
 0:     assimp ptr: 0n
 0:   initializing Loader ............................................ 0.049 s
 0: initializing aardvark .................................... [0.03x] 0.325 s
 0: [CooTransformation] installing CooTransformationDefault.trl
 0: [CooTransformation] installing ExoMarsRover_VariousCameras.xml
 0: [CooTransformation] installing GraphObject3dDefault.trl
 0: [CooTransformation] installing HiRISE.txt
 0: [CooTransformation] installing InstrumentPlatformsDefault.trl
 0: [CooTransformation] installing InternationalisationRegistryDefault.trl
 0: [CooTransformation] installing pck00010.tpc
 0: [CooTransformation] installing ProgressDefault.trl
 0: [CooTransformation] installing M20_waypoints.json
 0: [CooTransformation] initializing at C:\Users\Kevin Streicher\AppData\Roaming\Pro3D\JR\CooTransformationConfig, logging to C:\Users\Kevin Streicher\AppData\Roaming\Pro3D\JR\logs
[2022-02-23 17:37:16.085769][trace]:  Initialized console logger
[2022-02-23 17:37:16.086770][trace]:  Initialized file logger C:\Users\Kevin Streicher\AppData\Roaming\Pro3D\JR\logs/CooTransformation.log
[2022-02-23 17:37:16.091775][info]:  Initializing SPICE version 'CSPICE_N0066'.
[2022-02-23 17:37:16.123805][info]:  Successfully loaded SPICE kernels from C:\Users\Kevin Streicher\AppData\Roaming\Pro3D\JR\CooTransformationConfig.
 0: [CooTransformation] Successfully initialized CooTrafo
 0: [InstrumentPlatforms] Instrument dll sucessfully initialized
 0: OpenGL 4.5 working
 0: initializing OpenGL runtime ..............................................
 0:   vendor:   "NVIDIA Corporation"
 0:   renderer: "NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2"
 0:   version:  OpenGL 4.5.0 / GLSL 4.5.0  Core
 0: initializing OpenGL runtime ...................................... 0.109 s
 0: PRo3D Viewer - Version: 4.0.2 - Snapshots; powered by Aardvark
**Unhandled exception. System.Exception: reactivate Snapshots
   at Program.startApplication(CLStartupArgs startupArgs) in E:\repositories\Pro3D\src\PRo3D.Snapshots\Program.fs:line 164
   at Program.main(String[] argv) in E:\repositories\Pro3D\src\PRo3D.Snapshots\Program.fs:line 270**
```

[Scenes.zip](https://github.com/pro3d-space/PRo3D/files/8126121/Scenes.zip)

**Comment by haraldsteinlechner** [comment]
@RebeccaNowak any ideas what happened to ViewerApp.startAndReturnMModel

**Comment by RebeccaNowak** [comment]
I think @ThomasOrtner disabled it after merging.

**Comment by NoxMortem** [comment]
@haraldsteinlechner  This is the latest release from the release page: [4.6.1-prerelease1](https://github.com/pro3d-space/PRo3D/releases/tag/4.6.1-prerelease1)

The scene file is incompatible with the following versions and both do not have a tab "SequBookmark" so I assume this is a new feature not available there yet.:
- Latest stable release [4.0.3](https://github.com/pro3d-space/PRo3D/releases/tag/4.0.3)
- [4.2.0-prerelease1](https://github.com/pro3d-space/PRo3D/releases/tag/4.2.0-prerelease1)

```
6: WARNING: [PRo3D] SceneLoading.loadScene failed: "don't know version 2  of Scene"
 6: Stacktrace: "   at PRo3D.SceneLoaderModule.loadScene(String path, Model m, IRuntime runtime, IFramebufferSignature signature)
 6:    at PRo3D.SceneLoading.loadNewStyleScene(Model m, IRuntime runtime, IFramebufferSignature signature, String sceneFile)"
 6: ERROR: [PRo3D] could not load file: ...\test.pro3d, error: [PRo3D] SceneLoading.loadScene failed: "don't know version 2  of Scene"
```

**Comment by chris-traxler** [comment]
Fixed when merged with the new version.
