### ISSUE TITLE
latest pre-release won't start on windows 11

### ISSUE THREAD

**Issue by AndrewAnnex** [pro3d-space/PRo3D#235]
seems to be misconfigured somewhere but not sure where to look 

```
[2022-09-22 22:50:30.156847][trace]:  Initialized console logger
[2022-09-22 22:50:30.157848][trace]:  Initialized file logger C:\Users\Andrew\AppData\Roaming\Pro3D\JR\logs/CooTransformation.log
[2022-09-22 22:50:30.157848][info]:  Initializing SPICE version 'CSPICE_N0066'.
[2022-09-22 22:50:30.189844][info]:  Successfully loaded SPICE kernels from C:\Users\Andrew\AppData\Roaming\Pro3D\JR\CooTransformationConfig.
Unhandled exception. System.ArgumentException: [Framebuffer] samples must be one of set [1; 2; 4; 8; 16; 32; 64] but got 0
   at Aardvark.Rendering.ResourceValidation.Framebuffers.Utils.failf@261-2.Invoke(String str)
   at Aardvark.Rendering.ResourceValidation.Framebuffers.validateSignatureParams(FSharpMap`2 colorAttachments, FSharpOption`1 depthStencilAttachment, Int32 samples, Int32 layers)
   at Aardvark.Rendering.GL.Runtime.CreateFramebufferSignature(FSharpMap`2 colorAttachments, FSharpOption`1 depthStencilAttachment, Int32 samples, Int32 layers, IEnumerable`1 perLayerUniforms)
   at Aardvark.Rendering.GL.Runtime.Aardvark.Rendering.IFramebufferRuntime.CreateFramebufferSignature(FSharpMap`2 colorAttachments, FSharpOption`1 depthStencilAttachment, Int32 samples, Int32 layers, IEnumerable`1 perLayerUniforms)
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at Aardvark.Rendering.IFramebufferRuntimeExtensions.CreateFramebufferSignature(IFramebufferRuntime this, FSharpMap`2 attachments, Int32 samples, Int32 layers, IEnumerable`1 perLayerUniforms)
   at Aardvark.Application.Slim.OpenGL.createSurface(Runtime runtime, WindowConfig cfg, Glfw glfw, WindowHandle* win)
   at Aardvark.Application.Slim.OpenGL.interop@289.Aardvark.Glfw.IWindowInterop.CreateSurface(IRuntime runtime, WindowConfig cfg, Glfw glfw, WindowHandle* win)
   at <StartupCode$Aardvark-Application-Slim>.$GLFW.CreateWindow@646.Invoke(Unit unitVar0)
   at Aardvark.Application.Slim.OpenGlApplication.createContext()
   at <StartupCode$Aardvark-Application-Slim-GL>.$Application.-ctor@356-1.Invoke(Unit arg10@)
   at Aardvark.Rendering.GL.Context..ctor(IRuntime runtime, FSharpFunc`2 createContext)
   at Aardvark.Application.Slim.OpenGlApplication..ctor(Boolean forceNvidia, DebugLevel debug, FSharpOption`1 shaderCachePath, Boolean hideCocoaMenuBar)
   at Program.main(String[] argv)
```

**Comment by AndrewAnnex** [comment]
@haraldsteinlechner what do you mean by "my driver"? If you are talking about the graphics card driver this machine has an nvidia 1080ti so it should be fairly up-to-date

**Comment by haraldsteinlechner** [comment]
thanks for the info about the gpu - while tracking it down we had several theories and definitely fixed a bug where we created multisampled windows even though multisampling is reported unsupported by the graphics card.
So, given that you use a 1080ti, this can't be the problem since multisampling is practically supported everywhere for decades. 
In conclusion, we might not have fixed the problem.
Remaining options:

1. the renderer not uses the dedicated gpu for some reason
2. some wrong configuration as suggested by you (maybe related to win11, i ruled this one out at least with amd cards)

If you test it, could you please attach the full log? On windows it is here: %APPDATA%\Pro3D\PRo3D.log
