### ISSUE TITLE
screenshot folder selection does not work on macos

### ISSUE THREAD

**Issue by AndrewAnnex** [pro3d-space/PRo3D#252]
pressing the screenshot folder button in the UI causes the following error.
pro3d seems to assume explorer.exe exists for macos, which doesn't of course. 

```
 9: ERROR
 9:   [media] update function failed with: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'explorer.exe' with working directory '/Applications/PRo3D.Viewer.app/Contents/build/build'. No such file or directory
 9:      at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
 9:      at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
 9:      at System.Diagnostics.Process.Start()
 9:      at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
 9:      at System.Diagnostics.Process.Start(String fileName, String arguments)
 9:      at PRo3D.SimulatedViews.ScreenshotAppModule.update(String baseUrl, Int32 numberOfSamples, String outputPath, ScreenshotModel m, ScreenshotAction action)
 9:      at PRo3D.ViewerApp.updateViewer$cont@1522-41(Model m, ScreenshotAction msg, Unit unitVar)
 9:      at PRo3D.ViewerApp.updateViewer(IRuntime runtime, IFramebufferSignature signature, BlockingCollection`1 sendQueue, FSharpMailboxProcessor`1 mailbox, Model m, ViewerAction msg)
 9:      at <StartupCode$Aardvark-UI>.$App.doit@72-2.Invoke(Unit unitVar0)
 ```

**Comment by haraldsteinlechner** [comment]
thanks.

yes it is here: https://github.com/pro3d-space/PRo3D/blob/25e2de504b1870b88a41a3050fe65d5634524138/src/PRo3D.SimulatedViews/Screenshots/ScreenshotApp.fs#L73
it can be replaced by using electron's platform agnostic features - https://www.electronjs.org/de/docs/latest/api/shell to fix it.
